/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.scheduling.validation;

import com.netxforge.netxstudio.scheduling.Job;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.scheduling.Scheduling}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SchedulingValidator {
	boolean validate();

	boolean validateJobs(Job value);
}
