/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.generics.validation;

import com.netxforge.netxstudio.generics.MultiImage;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.generics.Company}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CompanyValidator {
	boolean validate();

	boolean validateIcons(MultiImage value);
	boolean validateName(String value);
	boolean validateRSSurl(String value);
	boolean validateShortName(String value);
	boolean validateSymbol(String value);
	boolean validateWebsite(String value);
}
