/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.generics.validation;

import com.netxforge.netxstudio.generics.Company;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.generics.Person}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PersonValidator {
	boolean validate();

	boolean validateCompanyRef(Company value);
	boolean validateEmail(String value);
	boolean validateFirstName(String value);
	boolean validateLastName(String value);
	boolean validateLogin(String value);
	boolean validatePassword(String value);
}
