/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.metrics.validation;

import com.netxforge.netxstudio.metrics.ObjectNameType;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.metrics.IdentifierDataKind}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IdentifierDataKindValidator {
	boolean validate();

	boolean validateObjectAttribute(String value);
	boolean validateObjectName(ObjectNameType value);
}
