/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.metrics.validation;

import org.eclipse.emf.common.util.EList;

import com.netxforge.netxstudio.generics.DateTimeRange;
import com.netxforge.netxstudio.metrics.MappingRecord;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.metrics.MappingStatistic}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MappingStatisticValidator {
	boolean validate();

	boolean validateFailedRecords(EList<MappingRecord> value);
	boolean validateMappingDuration(DateTimeRange value);
	boolean validateTotalRecords(int value);
}
