/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.metrics.validation;

import org.eclipse.emf.common.util.EList;

import com.netxforge.netxstudio.generics.Value;
import com.netxforge.netxstudio.metrics.KindHintType;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.metrics.MetricValueRange}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MetricValueRangeValidator {
	boolean validate();

	boolean validateMetricValues(EList<Value> value);
	boolean validateKindHint(KindHintType value);
	boolean validateName(String value);
	boolean validatePeriodHint(int value);
}
