/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.metrics.validation;

import org.eclipse.emf.common.util.EList;

import com.netxforge.netxstudio.metrics.Mapping;
import com.netxforge.netxstudio.metrics.MappingStatistic;
import com.netxforge.netxstudio.metrics.Metric;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.metrics.MetricSource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MetricSourceValidator {
	boolean validate();

	boolean validateMetricRefs(EList<Metric> value);
	boolean validateMetricMapping(Mapping value);
	boolean validateStatistics(EList<MappingStatistic> value);
	boolean validateMetricLocation(String value);
	boolean validateName(String value);
}
