/*
 * generated by Xtext
 */
package com.netxforge;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SmiRuntimeModule extends com.netxforge.AbstractSmiRuntimeModule {

}
