/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.operators.validation;

import com.netxforge.netxstudio.operators.ExpansionExperience;
import com.netxforge.netxstudio.operators.Network;
import com.netxforge.netxstudio.operators.ResourceExpansion;
import com.netxforge.netxstudio.operators.Warehouse;

import com.netxforge.netxstudio.services.Service;
import com.netxforge.netxstudio.services.ServiceUser;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.operators.Operator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperatorValidator {
	boolean validate();

	boolean validateNetworks(EList<Network> value);
	boolean validateWarehouses(EList<Warehouse> value);
	boolean validateServices(EList<Service> value);
	boolean validateServiceUsers(EList<ServiceUser> value);
	boolean validateResourceExpansions(EList<ResourceExpansion> value);
	boolean validateExpansionExperiences(EList<ExpansionExperience> value);
}
