grammar com.netxforge.Netxscript with org.eclipse.xtext.xbase.Xbase

generate netxscript "http://www.netxforge.com/Netxscript"
import "http://www.eclipse.org/xtext/xbase/Xbase" as xbase

Model:
	block=SpecialBlockExpression;
	
SpecialBlockExpression returns xbase::XBlockExpression:
	{SpecialBlockExpression}
	((expressions+=XExpressionInsideBlock | imports+=Import) ';'?)*
;

Import :
	'import' importedNamespace=QualifiedNameWithWildCard
;

QualifiedNameWithWildCard : 
	QualifiedName ('.*')?
;
