/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.services.validation;

import org.eclipse.emf.common.util.EList;

import com.netxforge.netxstudio.generics.Value;
import com.netxforge.netxstudio.services.ServiceUser;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.services.ServiceForecastUsers}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServiceForecastUsersValidator {
	boolean validate();

	boolean validateUserValues(EList<Value> value);
	boolean validateServiceUserRef(ServiceUser value);
}
