/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.services.validation;

import org.eclipse.emf.common.util.EList;

import com.netxforge.netxstudio.services.CIID;
import com.netxforge.netxstudio.services.Service;
import com.netxforge.netxstudio.services.ServiceClassType;
import com.netxforge.netxstudio.services.ServiceDistribution;
import com.netxforge.netxstudio.services.ServiceForecast;
import com.netxforge.netxstudio.services.ServiceMonitor;
import com.netxforge.netxstudio.services.ServiceUser;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.services.Service}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServiceValidator {
	boolean validate();

	boolean validateCIID(EList<CIID> value);
	boolean validateServices(EList<Service> value);
	boolean validateServiceForecasts(EList<ServiceForecast> value);
	boolean validateServiceMonitors(EList<ServiceMonitor> value);
	boolean validateServiceUserRefs(EList<ServiceUser> value);
	boolean validateServiceDistribution(ServiceDistribution value);
	boolean validateServiceCategory(String value);
	boolean validateServiceClass(ServiceClassType value);
	boolean validateServiceDescription(String value);
	boolean validateServiceName(String value);
}
