/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.services.validation;

import org.eclipse.emf.common.util.EList;

import com.netxforge.netxstudio.generics.DateTimeRange;
import com.netxforge.netxstudio.operators.ResourceForecast;
import com.netxforge.netxstudio.services.ServiceForecastUsers;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.services.ServiceForecast}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ServiceForecastValidator {
	boolean validate();

	boolean validatePeriod(DateTimeRange value);
	boolean validateServiceForecastUsers(EList<ServiceForecastUsers> value);
	boolean validateResourceForecasts(EList<ResourceForecast> value);
	boolean validateName(String value);
	boolean validateRevision(String value);
}
