/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.generics.validation;

import com.netxforge.netxstudio.generics.Person;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.generics.Meta}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MetaValidator {
	boolean validate();

	boolean validateAuthor(Person value);
	boolean validateDescription(String value);
	boolean validateVersion(String value);
}
