<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="smi" nsURI="http://www.netxforge.com/Smi" nsPrefix="smi">
  <eClassifiers xsi:type="ecore:EClass" name="Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//Assignment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" eType="#//ObjectIdentifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="macro" eType="#//Macro"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectIdentifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oidValue" eType="#//ObjectIdentifierValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectIdentifierValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="descriptorReference" eType="#//ObjectIdentifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subIds" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" eType="#//Scope"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Macro">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeNotations" upperBound="-1"
        eType="#//TypeAssignment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueNotation" eType="#//MacroValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innerTypes" upperBound="-1"
        eType="#//TypeDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeAssignment"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParamAssignment" eSuperTypes="#//TypeAssignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="param" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//TypeNotation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeNotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//MacroValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeReferenceExt"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeReference" eSuperTypes="#//TypeAssignment #//TypeNotation #//TypeReferenceExt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//TypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueTypes" upperBound="-1"
        eType="#//ValueType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="#//ParamAssignment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeReferenceExt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simpleType" eType="#//ASN1_TYPE"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="macroValue" eType="#//MacroValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MacroValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//MACRO_VALUE_TYPE"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MACRO_VALUE_TYPE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valLiteral" eType="#//MACRO_VALUE_CAP"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="update" eType="#//UpdateType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MACRO_VALUE_CAP">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="literal" eType="#//VALUE_CAP_LITERALS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VALUE_CAP_LITERALS">
    <eLiterals name="oiLiteral" literal="OBJECT IDENTIFIER"/>
    <eLiterals name="ia5StringLiteral" value="1" literal="IA5String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASN1_TYPE"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASN1_SIMPLE" eSuperTypes="#//ASN1_TYPE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valuePairs" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASN1_SUBTYPE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ranges" upperBound="-1"
        eType="#//ASN1_RANGE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASN1_RANGE">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASN1_CHOICE" eSuperTypes="#//ASN1_TYPE">
    <eStructuralFeatures xsi:type="ecore:EReference" name="choices" upperBound="-1"
        eType="#//ASN1_CHOICE_ENTRY" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASN1_CHOICE_ENTRY">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueType" eType="#//ValueType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASN1_OCTET_STRING" eSuperTypes="#//ASN1_SIMPLE"/>
</ecore:EPackage>
