/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.generics.validation;

import javax.xml.datatype.XMLGregorianCalendar;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.generics.Lifecycle}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LifecycleValidator {
	boolean validate();

	boolean validateConstructionDate(XMLGregorianCalendar value);
	boolean validateInServiceDate(XMLGregorianCalendar value);
	boolean validateOutOfServiceDate(XMLGregorianCalendar value);
	boolean validatePlannedDate(XMLGregorianCalendar value);
	boolean validateProposed(XMLGregorianCalendar value);
}
