/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.metrics.validation;

import com.netxforge.netxstudio.metrics.DataKind;

import com.netxforge.netxstudio.metrics.MappingXLSColumn;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.metrics.MappingXLS}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MappingXLSValidator {
	boolean validate();

	boolean validateMappingColumns(EList<MappingXLSColumn> value);

	boolean validateColumnHeaders(EList<String> value);
	boolean validateColumnDataKind(EList<DataKind> value);
	boolean validateFirstDataRow(int value);
	boolean validateHeaderRow(int value);
	boolean validateSheetNumber(int value);
}
