/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.metrics.validation;

import com.netxforge.netxstudio.metrics.DataKind;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.metrics.MappingXLSColumn}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MappingXLSColumnValidator {
	boolean validate();

	boolean validateDataType(DataKind value);
	boolean validateColumnName(String value);
	boolean validateColumnRow(int value);
}
