/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.operators.validation;

import com.netxforge.netxstudio.generics.Value;

import com.netxforge.netxstudio.library.Equipment;
import com.netxforge.netxstudio.library.Function;

import com.netxforge.netxstudio.operators.MarkerKind;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.operators.Marker}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MarkerValidator {
	boolean validate();

	boolean validateEquipmentRef(Equipment value);
	boolean validateFunctionRef(Function value);
	boolean validateMarkerValueRef(Value value);
	boolean validateDescription(String value);
	boolean validateKind(MarkerKind value);
}
