/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.operators.validation;

import com.netxforge.netxstudio.generics.DiagramInfo;
import com.netxforge.netxstudio.generics.Person;

import com.netxforge.netxstudio.metrics.MetricSource;

import com.netxforge.netxstudio.operators.EquipmentRelationship;
import com.netxforge.netxstudio.operators.FunctionRelationship;
import com.netxforge.netxstudio.operators.Network;
import com.netxforge.netxstudio.operators.Node;

import javax.xml.datatype.XMLGregorianCalendar;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.operators.Network}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NetworkValidator {
	boolean validate();

	boolean validateDiagrams(EList<DiagramInfo> value);
	boolean validateNodes(EList<Node> value);
	boolean validateNetworks(EList<Network> value);
	boolean validateFunctionRelationships(EList<FunctionRelationship> value);
	boolean validateEquipmentRelationships(EList<EquipmentRelationship> value);
	boolean validateMetricSources(EList<MetricSource> value);
	boolean validateCreatedByRef(Person value);
	boolean validateCreatedDate(XMLGregorianCalendar value);
	boolean validateDescription(String value);
	boolean validateName(String value);
}
