/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.operators.validation;

import org.eclipse.emf.common.util.EList;

import com.netxforge.netxstudio.generics.Lifecycle;
import com.netxforge.netxstudio.generics.Person;
import com.netxforge.netxstudio.geo.Room;
import com.netxforge.netxstudio.library.NodeType;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.operators.Node}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeValidator {
	boolean validate();

	boolean validateLifecycle(Lifecycle value);
	boolean validateNodeType(EList<NodeType> value);

	boolean validateFunctions(EList<NodeType> value);
	boolean validateCreatedByRef(Person value);
	boolean validateNodeID(String value);
	boolean validateOriginalNodeTypeRef(NodeType value);
	boolean validateRoomRef(Room value);
}
