/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.operators.validation;

import org.eclipse.emf.ecore.EObject;

import com.netxforge.netxstudio.operators.Node;
import com.netxforge.netxstudio.protocols.Protocol;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.operators.Relationship}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RelationshipValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateNodeID1Ref(Node value);
	boolean validateNodeID2Ref(Node value);
	boolean validateProtocolRef(Protocol value);

	boolean validateProtocolRef(EObject value);
}
