/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.models.xtextwrapper.validation;

import org.eclipse.xtext.xbase.XBlockExpression;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.models.xtextwrapper.NetXScriptWrapper}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NetXScriptWrapperValidator {
	boolean validate();

	boolean validateAsString(String value);
	boolean validateXblock(XBlockExpression value);
}
