/*
* generated by Xtext
*/
package com.netxforge.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class NetxscriptOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
