/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.metrics.validation;

import com.netxforge.netxstudio.metrics.ValueKindType;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.metrics.ValueDataKind}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValueDataKindValidator {
	boolean validate();

	boolean validateValueKind(ValueKindType value);
}
