/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.geo.validation;

import org.eclipse.emf.common.util.EList;

import com.netxforge.netxstudio.generics.MultiImage;
import com.netxforge.netxstudio.geo.Site;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.geo.Country}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CountryValidator {
	boolean validate();

	boolean validateSites(EList<Site> value);
	boolean validateIcons(MultiImage value);
	boolean validateCountryCode(String value);
	boolean validateName(String value);
}
