/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.netxforge.netxstudio.geo.validation;

import org.eclipse.emf.common.util.EList;

import com.netxforge.netxstudio.geo.Room;

/**
 * A sample validator interface for {@link com.netxforge.netxstudio.geo.Site}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SiteValidator {
	boolean validate();

	boolean validateRooms(EList<Room> value);
	boolean validateArea(String value);
	boolean validateCity(String value);
	boolean validateHousenumber(String value);
	boolean validateLatitude(String value);
	boolean validateLongitude(String value);
	boolean validateName(String value);
	boolean validatePostalcode(String value);
	boolean validateRegion(String value);
	boolean validateSreet(String value);
}
