/*
* generated by Xtext
*/
package com.netxforge.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;
import com.netxforge.services.NetxscriptGrammarAccess;

public class NetxscriptParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private NetxscriptGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.netxforge.parser.antlr.internal.InternalNetxscriptParser createParser(XtextTokenStream stream) {
		return new com.netxforge.parser.antlr.internal.InternalNetxscriptParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Mod";
	}
	
	public NetxscriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(NetxscriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
