/*
* generated by Xtext
*/
package com.netxforge.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class SmiProposalProvider extends com.netxforge.ui.contentassist.AbstractSmiProposalProvider {

}
