/*
 * generated by Xtext
 */
package com.netxforge.ui.contentassist

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class SmiProposalProvider extends AbstractSmiProposalProvider {
}
