/**
 * generated by Xtext
 */
package com.netxforge.scoping;

import com.netxforge.smi.Attribute;
import com.netxforge.smi.Macro;
import com.netxforge.smi.SmiPackage.Literals;
import com.netxforge.smi.TypeNotation;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it
 */
@SuppressWarnings("all")
public class SmiScopeProvider extends AbstractDeclarativeScopeProvider {
  public IScope scope_Attribute_paramRef(final Attribute attr, final EReference eRef) {
    IScope _xblockexpression = null;
    {
      EObject _eContainer = attr.eContainer();
      final com.netxforge.smi.Object o = ((com.netxforge.smi.Object) _eContainer);
      Macro _macroRef = o.getMacroRef();
      TypeNotation _typeNotation = _macroRef.getTypeNotation();
      IScope _scope = super.getScope(_typeNotation, Literals.TYPE_NOTATION__TYPE_NOTATIONS);
      _xblockexpression = (_scope);
    }
    return _xblockexpression;
  }
}
