/*
 * generated by Xtext
 */
package com.netxforge.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.resource.IResourceServiceProvider;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;

import com.google.inject.Scopes;
import com.netxforge.scoping.DynamixCDOScopeProvider;
import com.netxforge.scoping.DynamixCDOResourceDescriptions;
import com.netxforge.ui.scoping.UICDOResourceServiceProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class NetxscriptUiModule extends
		com.netxforge.ui.AbstractNetxscriptUiModule {
	public NetxscriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	// Also override the IResourceDescriptions, as the shared state overrides
	// us.
	// Override generated, ResourceSet based.
	public void configureIResourceDescriptions(com.google.inject.Binder binder) {
		binder.bind(org.eclipse.xtext.resource.IResourceDescriptions.class)
				.to(DynamixCDOResourceDescriptions.class).in(Scopes.SINGLETON);
	}

	public Class<? extends IResourceServiceProvider> bindIResourceServiceProvider() {
		return UICDOResourceServiceProvider.class;
	}
	
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return null;
	}
	
	public void configureIGlobalScopeProvider(com.google.inject.Binder binder) {
		binder.bind(org.eclipse.xtext.scoping.IGlobalScopeProvider.class).to(
				DynamixCDOScopeProvider.class).in(Scopes.SINGLETON);
	}

}
